Fix the comparing boundary points of `concept-range-bp-set`
whatwg/dom pull request #925
Opened 2020-11-17 12:08 UTC by chansuke

Fixes #924

2020-11-17 13:38 UTC, annevk approved these changes
Thanks, this looks good. @edg2s FYI.

2020-11-17 13:39 UTC, annevk commented
@chansuke if you want you can add your name to the Acknowledgments section.

2020-11-17 15:54 UTC, edg2s commented
+1

2020-11-17 15:59 UTC, edg2s requested changes

2020-11-17 15:59 UTC, edg2s commented on dom.bs
> +     <var>range</var>'s <a for=range>end</a>, set
this should be "start"

2020-11-17 15:59 UTC, edg2s commented on dom.bs
> +     <var>range</var>'s <a for=range>end</a>
this should be "start"

2020-11-17 16:04 UTC, edg2s commented
"start" was inadvertently changed to "end", presumably and copy-paste error, as can be seen in the HTML diff:
![image](https://user-images.githubusercontent.com/180672/99414224-83977200-28ee-11eb-9997-852403ad5dec.png)

2020-11-17 23:37 UTC, chansuke commented
@edg2s (CC: @annevk )I appreciate your review. I fixed and rebased it(since it's a small change).

2020-11-18 10:03 UTC, annevk approved these changes

2020-11-18 10:05 UTC, annevk commented
Thanks all!

2020-11-18 10:07 UTC, merged